# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MGBWaterBalance
                                 A QGIS plugin
 MGB Water Balance has the objective of carrying out the water balance of simulations carried out in the MGB. 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-04
        copyright            : (C) 2021 by HGE-IPH
        email                : rafinhamoz@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MGBWaterBalance class from file MGBWaterBalance.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mgb_water_balance import MGBWaterBalance
    return MGBWaterBalance(iface)
