# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BalancoHidricoDockWidget
                                 A QGIS plugin
 Esse plugin realiza o balanço hídrico de simualções do MGB.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-03-05
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Rafaela Oliveira
        email                : rafinhamoz@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from PyQt5 import QtGui, uic #nova janela
from PyQt5.QtCore import pyqtSignal #nova janela
from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal
from qgis.core import QgsProject
from PyQt5.QtWidgets import *
from PyQt5 import QtCore


#FORM_CLASS, _ = uic.loadUiType(os.path.join(
    #os.path.dirname(__file__), 'balanco_hidrico_dockwidget_base.ui'))
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'mgb_water_balance_dockwidget_base.ui'))


from PyQt5 import QtCore 
from PyQt5.QtWidgets import * 
from qgis.core import QgsProject


#class BalancoHidricoDockWidget(QtWidgets.QDockWidget, FORM_CLASS):
class MGBWaterBalanceDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        #super(BalancoHidricoDockWidget, self).__init__(parent)
        super(MGBWaterBalanceDockWidget, self).__init__(parent)
        self.setupUi(self)

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()

